# -*- coding: utf-8 -*-
"""통계학개론 과제_0501_고인정.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-KyURm9mnze1YBCypkadx8Fhk-f3peeR
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""# 문제 1. """

# 학생
students = pd.Series([
            88, 83, 83, 85, 94, 88, 91, 96, 
            89, 83, 81, 80, 84, 89, 83, 79
            ])

# 히스토그램
plt.hist(students)
plt.show()

# 상자그림
plt.boxplot(students)
plt.show()

students.describe()

# 다섯수치요약 (최소값, 제1사분위수, 중앙값, 제3사분위수, 최대값)

# 최소값
min_num = students.describe()['min']
print('최소값 : ', min_num)

# 제1사분위수
q1 = students.describe()['25%']
print('제1사분위수 : ', q1)

# 중앙값
q2 = students.describe()['50%']
print('중앙값 : ', q2)

# 제3사분위수
q3 = students.describe()['75%']
print('제3사분위수 : ', q3)

# 최대값
max_num = students.describe()['max']
print('최대값 :', max_num)

